INSERT INTO Category (id, category_name)
VALUES ("Shirts")
       ("Shorts")
       ("Music")
       ("Hats")              
       ("Shoes")  

INSERT INTO Product (id, product_name, price, stock)
VALUES ("Plain T-Shirt", 14.99, 14,)
       ("Running Sneakers", 90, 25)
       ("Brander Baseball Hat", 22.99, 12)
       ("Top 40 Music Compilation Vinyl Record", 12.99, 50)    
       ("Cargo Shorts", 29.99, 22)

INSERT INTO ProductTag (id, product_id, tag_id)
VALUES (1,6)
       (1,7)
       (1,8)
       (2,6)    
       (3,1)
       (3,3)
       (3,4)       
       (3,5)
       (4,1)
       (4,2)
       (4,8)
       (5,3)                            

INSERT INTO Tag (id, tag_name)
VALUES ("rock music")
       ("pop music")
       ("blue")
       ("red") 
       ("green") 
       ("white")  
       ("gold")  
       ("pop culture")                
